#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World" > /etc/nginx/html/index.html

cd /etc/nginx/html/
echo "Ceci n'est pas une page" > 404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://www.youtube.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
