#!/usr/bin/env bash
# Installs HAProxy version 2.6(LTS) with the following configurations:
# Enables management via the init script.
# Distributes requests using a round-robin algorithm.

sudo apt-get update
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get install -y haproxy=2.6.\*

echo "
frontend web-frontend
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 39210-web-01 100.26.177.87:80 check
        server 39210-web-02 34.207.222.225:80 check
" > /etc/haproxy/haproxy.cfg
sudo service haproxy reload
